NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
   # подключались к главному приложению с префиксом products/.
   path('news/', include('news.urls')),

   path('', include('protect.urls')),
   path('sign/', include('sign.urls')),
   path('accounts/', include('allauth.urls')),
]

news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import (
   PostList, PostDetail, PostSearch, PostCreate, PostUpdate, PostDelete, \
   CategoryListView, subscribe)


urlpatterns = [

   path('', PostList.as_view(), name='post_list'),
   path('<int:pk>', PostDetail.as_view(), name='post_detail'),
   path('search/', PostSearch.as_view(), name='post_search'),
   path('create/', PostCreate.as_view(), name='post_create'),
   path('articles/create/', PostCreate.as_view(), name='article_create'),
   path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
   path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('articles/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
   path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
]

news/models.py
from django.db import models
from datetime import datetime

from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.urls import reverse







class Author(models.Model):
    rating = models.IntegerField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    def update_rating(self):
        posts_rating = Post.objects.filter(author=self).aggregate(pr=Coalesce(Sum('rating'), 0))['pr']
        comm_rating = Comment.objects.filter(user=self.user).aggregate(cr=Coalesce(Sum('rating'), 0))['cr']
        post_comm_rating = Comment.objects.filter(post__author=self).aggregate(pcr=Coalesce(Sum('rating'), 0))['pcr']

    def __str__(self):
        return f'{self.user}: {self.rating}'

        print(posts_rating)
        print('--------')
        print(comm_rating)
        print('--------')
        print(post_comm_rating)

        self.rating = posts_rating * 3 + comm_rating + post_comm_rating
        self.save()



class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, blank=True, null=True, related_name='categories')

    def __str__(self):
        return self.name.title()



class Post(models.Model):
    news = 'NS'
    article = 'AR'

    POSITIONS = [
        (news, "Новость"),
        (article, "Статья")
    ]
    positions = models.CharField(max_length=2, choices=POSITIONS, default=news)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add = True)
    category = models.ManyToManyField(Category, through='PostCategory')
    header = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)


    def like(self):
        self.rating += 1
        self.save()


    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return f'{self.text[:124]}...'

    def __str__(self):
        return f'{self.text}: {self.header}: {self.create_time}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post}: {self.category}'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)
    comm_text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.create_time}: {self.comm_text}: {self.user}: {self.rating}'

news/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post

from datetime import date

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'header',
            'author',
            'text',
            'category',
        ]


    def clean_text(self):
        cleaned_data = super().clean()
        text = cleaned_data.get("text")
        if text is not None and len(text) < 20:
            raise ValidationError({
                "text": "Описание не может быть менее 20 символов."
            })

        return cleaned_data



    def clean(self):
        cleaned_data = super().clean()
        author = cleaned_data['author']
        today = date.today()
        post_limit = Post.objects.filter(author=author, create_time__date=today).count()
        if post_limit >= 3:
            raise ValidationError('Нельзя публиковать больше трех постов в сутки!!!')
        return cleaned_data

news/views.py
from django.shortcuts import render
from datetime import datetime
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import *
from .filters import PostFilter
from .forms import PostForm
from django.urls import reverse_lazy


from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.shortcuts import get_object_or_404
from .models import *






class PostList(ListView):
    model = Post
    ordering = '-create_time'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 2

    def get_queryset(self):
        # Получаем обычный запрос
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

   # def get_context_data(self, **kwargs):
    #    context = super().get_context_data(**kwargs)
     #   context['time_now'] = datetime.utcnow()
      #  context['next_sale'] = "Все свежие новости в эту среду!"
      #  return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        return context




class PostDetail(DetailView):
    # Модель всё та же, но мы хотим получать информацию по отдельному товару
    model = Post
    template_name = 'new.html'
    context_object_name = 'new'


class PostSearch(ListView):
    model = Post
    ordering = '-create_time'
    template_name = 'news_search.html'
    context_object_name = 'news'
    paginate_by = 2


    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context



class PostCreate(PermissionRequiredMixin, CreateView):
    form_class = PostForm
    model = Post
    template_name = 'new_edit.html'
    permission_required = ('news.add_post')


    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/news/articles/create/':
            post.positions = "AR"
        post.save()
        return super().form_valid(form)


class PostUpdate(PermissionRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'new_edit.html'
    permission_required = ('news.change_post')

    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/news/articles/edit/':
            post.positions = "AR"
        post.save()
        return super().form_valid(form)




class PostDelete(DeleteView):
    model = Post
    template_name = 'new_delete.html'
    success_url = reverse_lazy('post_list')


    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/news/articles/delete/':
            post.positions = "AR"
        post.save()
        return super().form_valid(form)

#from django.views.generic.edit import CreateView

class AddPost(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post', )


class ChangePost(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post', )
    # а дальше пишите код вашего представления


class CategoryListView(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_news_list'


    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(category=self.category).order_by('-create_time')
        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context

@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)


    message = 'Вы успешно подписались на рассылку новостей категории'
    return render(request, 'subscribe.html', {'category': category, 'message': message})

templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}
   <h1>Все новости</h1>
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}

       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>

   <h3>{{ time_now|date:'M d Y' }}</h3>
   <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о свежих новостях!" }} </h3>
   <h3>Количество постов: {{ news|length }}</h3>
   <hr>
   {% if category_news_list %}
       <table style="font-size: 20px;">
           <tr>
               <td>Заголовок</td>
               <td>Категории</td>
               <td>Текст</td>
               <td>Дата выпуска</td>
           </tr>

           {% for news in category_news_list %}

           <tr>
               <td>{{ news.header|censor }}</td>
               <td>
               {% for category in news.category.all %}
               <a href="{% url 'category_list' category.id %}">{{ category }}</a>
               {% endfor %}
               </td>
               <td>{{ news.text|truncatechars:20|censor }}</td>
               <td>{{ news.create_time|date:'M d Y' }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
   {% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
       <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>

       {% endif %}
   {% endif %}
{% endblock content %}

templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новые статьи за последнюю неделю</h2>
    <ul>
        {% for post in posts %}
            <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.header }}</a></li>
        {% endfor %}
    </ul>

</body>
</html>

templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/new.html
{% extends 'flatpages/default.html' %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1></h1>
   <h3>{{ time_now|date:'M d Y' }}</h3>
   <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о свежих новостях!" }} </h3>
   <hr>
   {% if new %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Категории</td>
               <td>Текст</td>
               <td>Дата выпуска</td>
           </tr>

           <tr>
               <td>{{ new.header }}</td>
               <td>
               {% for category in new.category.all %}
                 {{ category }}
               {% endfor %}
               </td>
               <td>{{ new.text }}</td>
               <td>{{ new.create_time|date:'M d Y' }}</td>
           </tr>
       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
{% endblock content %}

templates/new_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.header }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/new_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>

   <h3>{{ time_now|date:'M d Y' }}</h3>
   <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о свежих новостях!" }} </h3>
   <h3>Количество постов: {{ news|length }}</h3>
   <hr>
   {% if news %}
       <table style="font-size: 30px;">
           <tr>
               <td>Заголовок</td>
               <td>Категории</td>
               <td>Текст</td>
               <td>Дата выпуска</td>
               <td>Тип публикации</td>
           </tr>

           {% for news in news %}

           <tr>
               <td>{{ news.header|censor }}</td>
               <td>
               {% for category in news.category.all %}
               <a href="{% url 'category_list' category.id %}">{{ category }}</a>
               {% endfor %}
               </td>
               <td>{{ news.text|truncatechars:20|censor }}</td>
               <td>{{ news.create_time|date:'M d Y' }}</td>
               <td>{{ news.get_positions_display }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
   {% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
       <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>

       {% endif %}
   {% endif %}
{% endblock content %}

templates/news_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>


   <h3>{{ time_now|date:'M d Y' }}</h3>
   <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о свежих новостях!" }} </h3>
   <h3>Количество постов: {{ news|length }}</h3>
   <hr>
   {% if news %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Категории</td>
               <td>Текст</td>
               <td>Дата выпуска</td>
           </tr>

           {% for news in news %}

           <tr>
               <td>{{ news.header|censor }}</td>
               <td>
               {% for category in news.category.all %}
                 {{ category }}
               {% endfor %}
               </td>
               <td>{{ news.text|truncatechars:20|censor }}</td>
               <td>{{ news.create_time|date:'M d Y' }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новая <a href="{{ link }}">статья</a> в вашем любимом разделе!</h2>
        <p>{{ text }}</p>
</body>
</html>

templates/product.html
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Product -->
{% block title %}
Product
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

templates/products.html
{% endblock title %}

{% block content %}
   <h1>Все товары</h1>
   <h3>{{ time_now|date:'M d Y' }}</h3>
   <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }} </h3>

   <hr>
   {% if products %}
       <table>
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Категория</td>
               <td>Цена</td>
               <td>Количество</td>
           </tr>

           {% for product in products %}
           <tr>
               <td>{{ product.name }}</td>
               <td>{{ product.description|truncatewords:2 }}</td>
               <td>{{ product.category.name }}</td>
               <td>{{ product.price }}</td>
               <td>{{ product.quantity }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Товаров нет!</h2>
   {% endif %}
{% endblock content %}

templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1 class="text-center">{{ message }} {{ category }}</h1>
{% endblock %}